force-app/main/default/objects/Lead/fields/Benefice_attendus__c.field-meta.xml
<CustomField>
    <fullName>Benefice_attendus__c</fullName>
    <label>Bénéfice attendus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Augmentation de vos ventes</fullName>
            </value>
            <value>
                <fullName>Amélioration des vos marges, rentabilité, profitabilité</fullName>
            </value>
            <value>
                <fullName>Baisse des coûts</fullName>
            </value>
            <value>
                <fullName>Une meilleur qualité de services</fullName>
            </value>
            <value>
                <fullName>Une meilleur motivation des salariés</fullName>
            </value>
            <value>
                <fullName>Développer les compétences de vos salariés</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Date_souhaite__c.field-meta.xml
<CustomField>
    <fullName>Date_souhaite__c</fullName>
    <label>Date souhaité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Num_SIREN__c.field-meta.xml
<CustomField>
    <fullName>Num_SIREN__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Système d&apos;identification du répertoire des entreprises. Il est composé de 9 chiffres</inlineHelpText>
    <label>Numéro de SIREN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Opco__c.field-meta.xml
<CustomField>
    <fullName>Opco__c</fullName>
    <label>Opco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AKTO</fullName>
            </value>
            <value>
                <fullName>OPCO - entreprise de proximité</fullName>
            </value>
            <value>
                <fullName>ADFAS</fullName>
            </value>
            <value>
                <fullName>ATLAS</fullName>
            </value>
            <value>
                <fullName>UNIFORMATION</fullName>
            </value>
            <value>
                <fullName>OCAPIAT</fullName>
            </value>
            <value>
                <fullName>2I</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION</fullName>
            </value>
            <value>
                <fullName>MOBILITES</fullName>
            </value>
            <value>
                <fullName>SANTE</fullName>
            </value>
            <value>
                <fullName>OPCOMMERCE</fullName>
            </value>
            <value>
                <fullName>AGIFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Raison_Formation__c.field-meta.xml
<CustomField>
    <fullName>Raison_Formation__c</fullName>
    <label>Raison de Formation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Difficulté économique</fullName>
            </value>
            <value>
                <fullName>Mieux mesurer la performance de votre activité</fullName>
            </value>
            <value>
                <fullName>Mutations technologiques (Digitalisation)</fullName>
            </value>
            <value>
                <fullName>Développez vos ventes</fullName>
            </value>
            <value>
                <fullName>Mieux gérer la clientèle</fullName>
            </value>
            <value>
                <fullName>la règlementation (obligation légale : sécurité, hygiène, allergènes....)</fullName>
            </value>
            <value>
                <fullName>Assurer une meilleur qualité et d&apos;hygiène</fullName>
            </value>
            <value>
                <fullName>Développer les compétences de vos salariés</fullName>
            </value>
            <value>
                <fullName>Favoriser la mobilité et les promotions internes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/WS_GoogleFormManager.cls
global class WS_GoogleFormManager {

    webservice static String updateLead(String leadId, String email, String lastName, String company, String status, String ownerId, Boolean isUnreadByOwner, 
                                        String numSiren, String opco, String raisonFormation, String beneficeAttendus, String dateSouhaite, Integer numberOfEmployees, String message) {
        try {
            // Retrieve the lead by Id
            Lead leadToUpdate = [SELECT Id FROM Lead WHERE Id = :leadId LIMIT 1];

            // Update lead fields
            leadToUpdate.Email = email;
            leadToUpdate.LastName = lastName;
            leadToUpdate.Company = company;
            leadToUpdate.Status = status;
            leadToUpdate.OwnerId = ownerId;
            leadToUpdate.IsUnreadByOwner = isUnreadByOwner;
          
            leadToUpdate.Num_SIREN__c = numSiren;
            leadToUpdate.Opco__c = opco;
            leadToUpdate.Raison_Formation__c = raisonFormation;
            leadToUpdate.Benefice_attendus__c = beneficeAttendus;
            leadToUpdate.Date_Souhaite__c = dateSouhaite;
            leadToUpdate.NumberOfEmployees = numberOfEmployees;
            leadToUpdate.Message__c = message;

            // Update lead
            update leadToUpdate;

            return 'Lead updated successfully.';
        } catch (Exception e) {
            return 'Error updating lead: ' + e.getMessage();
        }
    }
}