force-app/main/default/objects/Lead/fields/Benefice_attendus__c.field-meta.xml
<CustomField>
    <fullName>Benefice_attendus__c</fullName>
    <label>Bénéfice attendus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Augmentation de vos ventes</fullName>
            </value>
            <value>
                <fullName>Amélioration des vos marges, rentabilité, profitabilité</fullName>
            </value>
            <value>
                <fullName>Baisse des coûts</fullName>
            </value>
            <value>
                <fullName>Une meilleur qualité de services</fullName>
            </value>
            <value>
                <fullName>Une meilleur motivation des salariés</fullName>
            </value>
            <value>
                <fullName>Développer les compétences de vos salariés</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Date_souhaite__c.field-meta.xml
<CustomField>
    <fullName>Date_souhaite__c</fullName>
    <label>Date souhaité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Intra_inter__c.field-meta.xml
<CustomField>
    <fullName>Intra_inter__c</fullName>
    <label>Intra/ inter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Une formation en intra-entreprise (formation délivrée exclusivement à vous)</fullName>
            </value>
            <value>
                <fullName>Une formation en inter-entreprise (formation qui réunit plusieurs entreprise)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lieux_formation__c.field-meta.xml
<CustomField>
    <fullName>Lieux_formation__c</fullName>
    <label>Lieux de la formation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Au Kremlin Bicêtre dans les locaux de Des-Click formation</fullName>
            </value>
            <value>
                <fullName>Dans vos locaux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Num_SIREN__c.field-meta.xml
<CustomField>
    <fullName>Num_SIREN__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Système d&apos;identification du répertoire des entreprises. Il est composé de 9 chiffres</inlineHelpText>
    <label>Numéro de SIREN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Opco__c.field-meta.xml
<CustomField>
    <fullName>Opco__c</fullName>
    <label>Opco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AKTO</fullName>
            </value>
            <value>
                <fullName>OPCO - entreprise de proximité</fullName>
            </value>
            <value>
                <fullName>ADFAS</fullName>
            </value>
            <value>
                <fullName>ATLAS</fullName>
            </value>
            <value>
                <fullName>UNIFORMATION</fullName>
            </value>
            <value>
                <fullName>OCAPIAT</fullName>
            </value>
            <value>
                <fullName>2I</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION</fullName>
            </value>
            <value>
                <fullName>MOBILITES</fullName>
            </value>
            <value>
                <fullName>SANTE</fullName>
            </value>
            <value>
                <fullName>OPCOMMERCE</fullName>
            </value>
            <value>
                <fullName>AGIFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Raison_Formation__c.field-meta.xml
<CustomField>
    <fullName>Raison_Formation__c</fullName>
    <label>Raison de Formation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Difficulté économique</fullName>
            </value>
            <value>
                <fullName>Mieux mesurer la performance de votre activité</fullName>
            </value>
            <value>
                <fullName>Mutations technologiques (Digitalisation)</fullName>
            </value>
            <value>
                <fullName>Développez vos ventes</fullName>
            </value>
            <value>
                <fullName>Mieux gérer la clientèle</fullName>
            </value>
            <value>
                <fullName>la règlementation (obligation légale : sécurité, hygiène, allergènes....)</fullName>
            </value>
            <value>
                <fullName>Assurer une meilleur qualité et d&apos;hygiène</fullName>
            </value>
            <value>
                <fullName>Développer les compétences de vos salariés</fullName>
            </value>
            <value>
                <fullName>Favoriser la mobilité et les promotions internes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GoogleFormWS.cls
@RestResource(urlMapping='/v1/googleform2')
global with sharing class GoogleFormWS {
    @HttpGet
    global static Lead getLeadByEmail() {
        RestRequest request = RestContext.request;
        String email = request.requestURI.substring(request.requestURI.lastIndexOf('/') + 1);
        
        try {
            // Query for the lead with the provided email
            Lead lead = [SELECT Id FROM Lead WHERE Email = :email LIMIT 1];
            return lead;
        } catch (QueryException e) {
            // Log error message
            System.debug('An error occurred while retrieving Salesforce lead: ' + e.getMessage());
            return null;
        }
    }
    @HttpPost
global static void updateSalesforceLead() {
    try {
        // Deserialize the request body into a map
        Map<String, Object> requestMap = (Map<String,Object>)JSON.deserializeUntyped(RestContext.request.requestBody.toString());
        System.debug('Request: ' + requestMap);
        
        // Retrieve lead fields from the request map
        String email = (String)requestMap.get('Email');
        String numSiren = (String)requestMap.get('Num_SIREN__c');
        String opco = (String)requestMap.get('Opco__c');
        String raisonFormation = (String)requestMap.get('Raison_Formation__c');
        String beneficeAttendus = (String)requestMap.get('Benefice_attendus__c');
        String dateSouhaite = (String)requestMap.get('Date_Souhaite__c');
        Integer numberOfEmployees = Integer.valueOf((String)requestMap.get('NumberOfEmployees'));
        String intraInter = (String)requestMap.get('Intra_inter__c');
        String lieuxFormation = (String)requestMap.get('Lieux_formation__c');
        String message = (String)requestMap.get('Message__c');
        
        // Query to check if a Lead with the provided email already exists
        Lead existingLead = [SELECT Id FROM Lead WHERE Email = :email LIMIT 1];
        
        // If a lead with the provided email exists, update its fields
        if (existingLead != null) {
            existingLead.Num_SIREN__c = numSiren;
            existingLead.Opco__c = opco;
            existingLead.Raison_Formation__c = raisonFormation;
            existingLead.Benefice_attendus__c = beneficeAttendus;
            existingLead.Date_Souhaite__c = dateSouhaite;
            existingLead.NumberOfEmployees = numberOfEmployees;
            existingLead.Intra_inter__c = intraInter;
            existingLead.Lieux_formation__c = lieuxFormation;
            existingLead.Message__c = message;
            
            // Update the existing lead
            update existingLead;
            
            // Log success message
            System.debug('Lead successfully updated with email: ' + existingLead.Email);
        } else {
            // Log message if no lead found with the provided email
            System.debug('No lead found with email: ' + email);
        }
    } catch (Exception e) {
        // Log error message
        System.debug('An error occurred while updating Salesforce lead: ' + e.getMessage());
    }
}

}