force-app/main/default/objects/Lead/fields/Benefice_attendus__c.field-meta.xml
<CustomField>
    <fullName>Benefice_attendus__c</fullName>
    <label>Bénéfice attendus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Augmentation de vos ventes</fullName>
            </value>
            <value>
                <fullName>Amélioration des vos marges, rentabilité, profitabilité</fullName>
            </value>
            <value>
                <fullName>Baisse des coûts</fullName>
            </value>
            <value>
                <fullName>Une meilleur qualité de services</fullName>
            </value>
            <value>
                <fullName>Une meilleur motivation des salariés</fullName>
            </value>
            <value>
                <fullName>Développer les compétences de vos salariés</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Date_souhaite__c.field-meta.xml
<CustomField>
    <fullName>Date_souhaite__c</fullName>
    <label>Date souhaité</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Intra_inter__c.field-meta.xml
<CustomField>
    <fullName>Intra_inter__c</fullName>
    <label>Intra/ inter</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Une formation en intra-entreprise (formation délivrée exclusivement à vous)</fullName>
            </value>
            <value>
                <fullName>Une formation en inter-entreprise (formation qui réunit plusieurs entreprise)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lieux_formation__c.field-meta.xml
<CustomField>
    <fullName>Lieux_formation__c</fullName>
    <label>Lieux de la formation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Au Kremlin Bicêtre dans les locaux de Des-Click formation</fullName>
            </value>
            <value>
                <fullName>Dans vos locaux</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Num_SIREN__c.field-meta.xml
<CustomField>
    <fullName>Num_SIREN__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Système d&apos;identification du répertoire des entreprises. Il est composé de 9 chiffres</inlineHelpText>
    <label>Numéro de SIREN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Opco__c.field-meta.xml
<CustomField>
    <fullName>Opco__c</fullName>
    <label>Opco</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AKTO</fullName>
            </value>
            <value>
                <fullName>OPCO - entreprise de proximité</fullName>
            </value>
            <value>
                <fullName>ADFAS</fullName>
            </value>
            <value>
                <fullName>ATLAS</fullName>
            </value>
            <value>
                <fullName>UNIFORMATION</fullName>
            </value>
            <value>
                <fullName>OCAPIAT</fullName>
            </value>
            <value>
                <fullName>2I</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION</fullName>
            </value>
            <value>
                <fullName>MOBILITES</fullName>
            </value>
            <value>
                <fullName>SANTE</fullName>
            </value>
            <value>
                <fullName>OPCOMMERCE</fullName>
            </value>
            <value>
                <fullName>AGIFICE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Raison_Formation__c.field-meta.xml
<CustomField>
    <fullName>Raison_Formation__c</fullName>
    <label>Raison de Formation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Difficulté économique</fullName>
            </value>
            <value>
                <fullName>Mieux mesurer la performance de votre activité</fullName>
            </value>
            <value>
                <fullName>Mutations technologiques (Digitalisation)</fullName>
            </value>
            <value>
                <fullName>Développez vos ventes</fullName>
            </value>
            <value>
                <fullName>Mieux gérer la clientèle</fullName>
            </value>
            <value>
                <fullName>la règlementation (obligation légale : sécurité, hygiène, allergènes....)</fullName>
            </value>
            <value>
                <fullName>Assurer une meilleur qualité et d&apos;hygiène</fullName>
            </value>
            <value>
                <fullName>Développer les compétences de vos salariés</fullName>
            </value>
            <value>
                <fullName>Favoriser la mobilité et les promotions internes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestWS_WEB.cls
@isTest
private class TestWS_WEB {
  @isTest
  static void setup() {
    Lead leadObj = new Lead(
      LastName = 'test value',
      Company = 'test value',
      Email = 'test@test.com'
    );
    insert leadObj;

    Test.startTest();
    String result = WS_WEB.updateRecord(
      leadObj.Email,
      '123456789',
      '2021-01-01',
      'ATLAS',
      'la règlementation (obligation légale : sécurité, hygiène, allergènes....)',
      'Une formation en intra-entreprise (formation délivrée exclusivement à vous)',
      'Augmentation de vos ventes',
      'Au Kremlin Bicêtre dans les locaux de Des-Click formation'
    );
    Test.stopTest();
    System.assertEquals(
      'Lead updated successfully.',
      result,
      'Unexpected result message.'
    );
    // System.assertEquals('123456789', leadObj.Num_SIREN__c, 'Unexpected SIREN number.');
    //    System.assertEquals('2021-01-01', leadObj.Date_souhaite__c, 'Unexpected date.');
    //    System.assertEquals('ATLAS', leadObj.Opco__c, 'Unexpected opco.');
    //    System.assertEquals('la règlementation (obligation légale : sécurité, hygiène, allergènes....)', leadObj.Raison_Formation__c, 'Unexpected reason.');
    //    System.assertEquals('Une formation en intra-entreprise (formation délivrée exclusivement à vous)', leadObj.Intra_inter__c, 'Unexpected intra-inter.');
    //    System.assertEquals('Augmentation de vos ventes', leadObj.Benefice_attendus__c, 'Unexpected benefits.');
    //    System.assertEquals('Au Kremlin Bicêtre dans les locaux de Des-Click formation', leadObj.Lieux_formation__c, 'Unexpected location.');
  }

  @isTest
  static void testUpdateRecord_NoLeadFound() {
    String result = WS_WEB.updateRecord(
      'noleadfound@test.com',
      '123456789',
      '2021-01-01',
      'ATLAS',
      'la règlementation (obligation légale : sécurité, hygiène, allergènes....)',
      'Une formation en intra-entreprise (formation délivrée exclusivement à vous)',
      'Augmentation de vos ventes',
      'Au Kremlin Bicêtre dans les locaux de Des-Click formation'
    );

    System.assertEquals(
      'No Lead found with the provided email.',
      result,
      'Unexpected result message.'
    );
  }

  @isTest
  static void testUpdateRecord_Exception() {
    String result = WS_WEB.updateRecord(
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    );

    System.assertEquals(
      'No Lead found with the provided email.',
      result,
      'Unexpected result message.'
    );
  }
}