force-app/main/default/objects/Opportunity/fields/Date_Formation__c.field-meta.xml
<CustomField>
    <fullName>Date_Formation__c</fullName>
    <label>Date De La Formation</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Formation_choisie__c.field-meta.xml
<CustomField>
    <fullName>Formation_choisie__c</fullName>
    <label>Formation choisie</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Formation HACCP</fullName>
            </value>
            <value>
                <fullName>Formation Piloter Mon Site</fullName>
            </value>
            <value>
                <fullName>Formation Galette Des Rois</fullName>
            </value>
            <value>
                <fullName>Formation Gâteaux de Fêtes</fullName>
            </value>
            <value>
                <fullName>Formation Google ADS</fullName>
            </value>
            <value>
                <fullName>Formation Management Pilotage</fullName>
            </value>
            <value>
                <fullName>Formation Négociation Commerciale</fullName>
            </value>
            <value>
                <fullName>Formation Réseaux Sociaux</fullName>
            </value>
            <value>
                <fullName>Formation Patisserie Classique</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityEvent.cls
public with sharing class OpportunityEvent {
    public static void createEvent(List<Opportunity> opportunities) {
        List<Event> eventsToInsert = new List<Event>();
        for(Opportunity opp : opportunities) {
            if (opp.Date_Formation__c != null) {
                Event newEvent = new Event();
                newEvent.Subject = opp.Formation_choisie__c + ' '+ 'pour'+' ' + opp.Account.Name;
                newEvent.Description = opp.Formation_choisie__c + ' '+ 'pour'+' ' + opp.Account.Name + ' ' + 'à' + ' ' + opp.Account.BillingStreet +', '+ opp.Account.BillingCity+' ' + opp.Account.BillingPostalCode;
                newEvent.StartDateTime = opp.Date_Formation__c;
                newEvent.EndDateTime = opp.Date_Fin_Formation__c;
                newEvent.WhatId = opp.Id;
                newEvent.OwnerId = UserInfo.getUserId();
                eventsToInsert.add(newEvent);
            }
        }
        insert eventsToInsert;
    }
}